### ISSUE TITLE
Let's keep Node and Angular files separate.

### ISSUE THREAD

**Issue by ibara** [ericabertolozzi/LunaApp#16]
Hello.

Could we please move Labs/Lab4/Lab4/server.js up one level to Labs/Lab4/server.js? We want to keep Node and Angular separate. The way you have it now meshes them together, which while it will work is probably not the best organizational methodology. You'll have to adjust the static middleware path in server.js after the move (and perhaps reinstall express/other Node deps at the new directory level), but it will be worthwhile.

**Comment by Manya14** [comment]
Server.js location has been adjusted. Thanks for pointing this out.
